{{- $secret := lookup "v1" "Secret" .Release.Namespace (include "vault-proxy-exporter.certifcateName" .) }}
{{ $ca := "" }}
{{ $key := "" }}
{{ $crt := "" }}
{{- if .Values.kubeRbacProxy.tls.certManagerIssuerRef }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "vault-proxy-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "vault-proxy-exporter.labels" . | nindent 4 }}
spec:
  secretName: {{ include "vault-proxy-exporter.certifcateName" . }}
  dnsNames:
    - {{ include "vault-proxy-exporter.fullname" . }}.{{ .Release.Namespace }}.svc
  issuerRef:
  {{- toYaml .Values.kubeRbacProxy.tls.certManagerIssuerRef | nindent 4 }}
  privateKey:
    rotationPolicy: Always
---
{{- else if .Values.kubeRbacProxy.tls.autogenerate }}
  {{- if and $secret (not .Values.kubeRbacProxy.tls.renew) }}
    {{- $ca = get $secret.data "ca.crt" }}
    {{- $key = get $secret.data "tls.key" }}
    {{- $crt = get $secret.data "tls.crt" }}
  {{- else }}
    {{- $serviceName := (printf "%s.%s.svc" (include "vault-proxy-exporter.fullname" .) .Release.Namespace)}}
    {{- $cert := genSelfSignedCert $serviceName nil (list $serviceName) 3650 }}
    {{- $ca = b64enc $cert.Cert }}
    {{- $key = b64enc $cert.Key }}
    {{- $crt = b64enc $cert.Cert }}
  {{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault-proxy-exporter.certifcateName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-proxy-exporter.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca }}
  tls.key: {{ $key }}
  tls.crt: {{ $crt }}
{{- end }}