{{- if and .Values.kubeRbacProxy.enabled .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vault-proxy-exporter.fullname" . }}
  labels:
    {{- include "vault-proxy-exporter.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vault-proxy-exporter.fullname" . }}
  labels:
    {{- include "vault-proxy-exporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vault-proxy-exporter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "vault-proxy-exporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}