apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault-proxy-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-proxy-exporter.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      {{- if .Values.kubeRbacProxy.enabled }}
      targetPort: https
      {{- else }}
      targetPort: http
      {{- end }}
      protocol: TCP
  selector:
    {{- include "vault-proxy-exporter.selectorLabels" . | nindent 4 }}
